/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semaforo;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class Semaforo extends javax.swing.JFrame {

    /**
     * Creates new form Semaforo
     */
    public Semaforo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblColores = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        lblDetener = new javax.swing.JLabel();
        lblPrecaucion = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblContinuar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourse/Gris.png"))); // NOI18N
        lblColores.setText("jLabel1");

        btnCambiar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        lblDetener.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblDetener.setForeground(new java.awt.Color(204, 204, 204));
        lblDetener.setText("Detener");

        lblPrecaucion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblPrecaucion.setForeground(new java.awt.Color(204, 204, 204));
        lblPrecaucion.setText("Precaucion");

        lblTitulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setText("Semaforo");

        lblContinuar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(204, 204, 204));
        lblContinuar.setText("Continuar");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblColores, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDetener)
                                .addGap(72, 72, 72)
                                .addComponent(btnCambiar)
                                .addContainerGap(135, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecaucion)
                                    .addComponent(lblContinuar))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiar)
                    .addComponent(lblDetener))
                .addGap(40, 40, 40)
                .addComponent(lblPrecaucion)
                .addGap(38, 38, 38)
                .addComponent(lblContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addComponent(lblColores, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        
        // TODO add your handling code here:
        
         int numRandom = (int)(Math.random()*3+1);
        int numAnterior = numRandom;
        
        if(numAnterior==1){
            numRandom=2;
        }
        
        if(numAnterior==2){
            numRandom=3;
        }
        
        if(numAnterior==3){
            numRandom=1;
        }
        
        
        switch (numRandom) {
            case 1:
                {
                    ImageIcon a = new ImageIcon("C:\\Users\\USUARIO\\Documents\\Semaforo_GretaVinueza\\semaforo\\src\\resourse\\Rojo.png");
                    lblColores.setIcon(a);
                    lblDetener.setForeground(Color.RED);
                    lblPrecaucion.setForeground(Color.LIGHT_GRAY);
                    lblContinuar.setForeground(Color.LIGHT_GRAY);
                    numRandom=numAnterior;
                    break;
                }
            case 2:
                {
                    ImageIcon a = new ImageIcon("C:\\Users\\USUARIO\\Documents\\Semaforo_GretaVinueza\\semaforo\\src\\resourse\\Amarillo.png");
                    lblColores.setIcon(a);
                    lblPrecaucion.setForeground(Color.YELLOW);
                    lblDetener.setForeground(Color.LIGHT_GRAY);
                    lblContinuar.setForeground(Color.LIGHT_GRAY);
                    numRandom=numAnterior;
                    break;
                }
            case 3:
                {   
                    ImageIcon a = new ImageIcon("C:\\Users\\USUARIO\\Documents\\Semaforo_GretaVinueza\\semaforo\\src\\resourse\\Verde.png");
                    lblColores.setIcon(a);
                    lblContinuar.setForeground(Color.GREEN);
                    lblPrecaucion.setForeground(Color.LIGHT_GRAY);
                    lblDetener.setForeground(Color.LIGHT_GRAY);
                    numRandom=numAnterior;
                    break;
                }
            default:
                break;
        }
        
                   
                    
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semaforo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblColores;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JLabel lblDetener;
    private javax.swing.JLabel lblPrecaucion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
